### ISSUE TITLE
help with error "None of the converters in the stack are operational"

### ISSUE THREAD

**Issue by ArthurLVVilla** [swissup/module-webp#1]
i'am on magento cloud v2.4.5p7
After following the installation commands and trying to run locally, I got this error
`Product images converted with errors:
None of the converters in the stack are operational`
![image](https://github.com/swissup/module-webp/assets/101821659/28896cc0-d35c-47df-9db9-4cab027d4a71)

![image](https://github.com/swissup/module-webp/assets/101821659/3a700a59-afea-4070-bdfe-50cc1a903c90)
![image](https://github.com/swissup/module-webp/assets/101821659/edc567e5-5166-452d-86bd-97f15beed3c2)
![image](https://github.com/swissup/module-webp/assets/101821659/a33ce565-4b72-485b-8606-bf70c1da1c00)

**Comment by 0m3r** [comment]
Looks like your gd does not support webp I think you need to upgrade your PHP.

In my case, I have the standalone line in phpinfo about it.

![Знімок екрана з 2024-05-21 12-14-13](https://github.com/swissup/module-webp/assets/412612/690287f0-2076-4d4e-9b25-51bc8cd6d340)

Please check available webp convertors
```
bin/magento swissup:webp:check -a 
```
and remember the better way to convert images to webp format is by using [cwebp](https://developers.google.com/speed/webp/docs/cwebp) tool using an exec call
